# Generated by Django 4.1.7 on 2023-06-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoriy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcategoria1', models.CharField(max_length=40)),
                ('Cat_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.categories')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcategoria2', models.CharField(max_length=40)),
                ('SubCat1_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.subcategoriy1')),
            ],
        ),
    ]
