# Generated by Django 4.1.7 on 2023-06-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategoriy1',
            new_name='SubCategory1',
        ),
    ]
