# Generated by Django 4.1.7 on 2023-06-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_rename_subcategoriy1_subcategory1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory1',
            old_name='Cat_ID',
            new_name='Cat',
        ),
        migrations.RenameField(
            model_name='subcategory2',
            old_name='SubCat1_ID',
            new_name='SubCat1',
        ),
    ]
